use urban_wasting_collection;

DROP TABLE IF EXISTS Staff;
create table Staff (
    `name` varchar(255) not null,
    `phone` varchar(10) default null,
    `email` varchar(255) not null unique,
    `id` int(7) primary key,
    `type` varchar(10) not null
);

INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Abbie Olford', 149805724, 'ksharrocks0@yelp.com', 1, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Abeu Le Clercq', 654429913, 'bstruthers1@hibu.com', 2, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Al MacCaghan', 786881412, 'wchanning2@last.fm', 3, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Anabal Micka', 475457233, 'bspinola3@sitemeter.com', 4, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Ansell Wills', 927510975, 'lveel4@wsj.com', 5, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Ashely Tonge', 128385059, 'mpedro5@wikipedia.org', 6, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Bartholomew Giannini', 79174708, 'tbernath6@soundcloud.com', 7, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Bartholomew Huntall', 158962586, 'cloos7@hostgator.com', 8, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Beauregard Haisell', 315413542, 'hsinnock8@cnbc.com', 9, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Berkie Lilleycrop', 824735681, 'evercruysse9@slate.com', 10, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Blaine Spinola', 814386362, 'pspurwaya@netscape.com', 11, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Brandy Zanicchi', 316346620, 'gsedgmanb@godaddy.com', 12, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Bren Struthers', 223698825, 'hfrippsc@chicagotribune.com', 13, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Brigham Scott', 682436823, 'jgrunderd@51.la', 14, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Caresse Jordin', 366708080, 'psadliere@yandex.ru', 15, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Carina Loos', 839868172, 'aolfordf@shutterfly.com', 16, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Cheryl Rappport', 53565704, 'ggusneyg@marriott.com', 17, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Chris Seldner', 463830428, 'lhethronh@google.cn', 18, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Christie Reynoldson', 746290095, 'dboutellieri@weebly.com', 19, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Cleon Lillyman', 474123235, 'raccombj@xinhuanet.com', 20, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Corinne Langshaw', 512610573, 'pscayk@tinyurl.com', 21, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Cortney Owlner', 897167364, 'ranticl@chron.com', 22, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Curtis Giovannelli', 57734383, 'atongem@booking.com', 23, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Dalia Unwin', 475519703, 'sdaintithn@pbs.org', 24, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Ddene Parncutt', 625152815, 'fkryskao@hud.gov', 25, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Dewey Dallinder', 827083421, 'okeirp@wordpress.com', 26, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Diego Priscott', 878749799, 'egrahameq@ibm.com', 27, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Dru Boutellier', 931963491, 'clangshawr@prnewswire.com', 28, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Earvin Grahame', 807309771, 'wboshiers@liveinternet.ru', 29, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Eduino Meni', 123911809, 'lgilyattt@cnbc.com', 30, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Emelyne Vercruysse', 126076727, 'ngrelkau@indiegogo.com', 31, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Ermina Attrie', 252628878, 'alev@jiathis.com', 32, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Eziechiele Maryska', 583869130, 'bscottw@seesaa.net', 33, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Frasco Kryska', 372783680, 'kshotboltx@archive.org', 34, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Gavin Sedgman', 175878972, 'ddallindery@newsvine.com', 35, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Gianni Goodram', 604380623, 'yexterz@fda.gov', 36, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Giustina Tenby', 363102434, 'rrosini10@acquirethisname.com', 37, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Greer Bonehill', 926483793, 'cgiovannelli11@cisco.com', 38, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Greggory Gusney', 646497120, 'blilleycrop12@deviantart.com', 39, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Guthry Hoys', 803356087, 'tcooke13@webs.com', 40, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Hollie Fripps', 808009329, 'slandis14@sun.com', 41, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Hoyt Sinnock', 265940580, 'mallwell15@gnu.org', 42, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Jillane McConnal', 502466519, 'cjordin16@ucoz.com', 43, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Joel Savary', 65763820, 'sogorman17@sogou.com', 44, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Jojo Leedes', 662586104, 'pfirsby18@discuz.net', 45, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Jorey Grunder', 195394537, 'bzanicchi19@4shared.com', 46, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Joshua Hellard', 766120731, 'nscotfurth1a@psu.edu', 47, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Kendra Shotbolt', 826566975, 'jsavary1b@imageshack.us', 48, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Kenon Sharrocks', 731244822, 'dunwin1c@umn.edu', 49, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Kettie Bascomb', 18223771, 'cowlner1d@tamu.edu', 50, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Kinna Thorpe', 749506023, 'rkumaar1e@harvard.edu', 51, 'Janitor');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Lanna Gilyatt', 671091206, 'msilkstone1f@washington.edu', 52, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Latisha McCabe', 112824748, 'jleedes1g@examiner.com', 53, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Layney Veel', 41672014, 'kthorpe1h@whitehouse.gov', 54, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Leonard Caig', 634951775, 'tbernardotti1i@theglobeandmail.com', 55, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Leslie Blagdon', 557443976, 'ptrevers1j@mac.com', 56, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Linet Ironside', 924895279, 'bhuntall1k@prlog.org', 57, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Lorelei Hethron', 187702148, 'sduberry1l@techcrunch.com', 58, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Lorelei Solway', 819317077, 'msevior1m@odnoklassniki.ru', 59, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Maitilde Allwell', 369308324, 'cseldner1n@feedburner.com', 60, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Matty Silkstone', 84344911, 'jhellard1o@bizjournals.com', 61, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Melicent Sevior', 932981207, 'wvasilmanov1p@marriott.com', 62, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Milty Pedro', 518746605, 'dpriscott1q@scientificamerican.com', 63, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Miof mela Bott', 527373955, 'gtenby1r@sfgate.com', 64, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Morty MacDermott', 177444781, 'gbonehill1s@bizjournals.com', 65, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Nelson Scotfurth', 39918495, 'creynoldson1t@twitter.com', 66, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Nettie Corradino', 164334703, 'lsolway1u@chicagotribune.com', 67, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Nikki Grelka', 903231327, 'bgiannini1v@mlb.com', 68, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Noel Grieg', 314220637, 'mmela1w@google.com', 69, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Norrie Filinkov', 966072372, 'sziemke1x@marriott.com', 70, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Orlan Keir', 31950956, 'rolden1y@elpais.com', 71, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Pammie Scay', 157704841, 'rbrookesbie1z@cnn.com', 72, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Panchito Spurway', 696573504, 'bhaisell20@clickbank.net', 73, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Petronilla Sadlier', 71384127, 'wsawday21@nature.com', 74, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Phip Guage', 965922235, 'pguage22@zdnet.com', 75, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Phyllis Firsby', 788070942, 'ngrieg23@macromedia.com', 76, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Pippo Trevers', 755039100, 'kbascomb24@mayoclinic.com', 77, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Rafe Masden', 967000912, 'lcaig25@time.com', 78, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Ranee Olden', 653719020, 'ggoodram26@cdc.gov', 79, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Reynold Kumaar', 45357392, 'ghoys27@wired.com', 80, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Roger Brookesbie', 474751952, 'zpetworth28@dmoz.org', 81, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Rosalinda Accomb', 168273595, 'rmuggleston29@symantec.com', 82, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Rowland Muggleston', 121314225, 'emaryska2a@answers.com', 83, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Royal Antic', 331254782, 'amicka2b@nifty.com', 84, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Rube Rosini', 51546497, 'lblagdon2c@mit.edu', 85, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Sallee Girton', 918382761, 'dparncutt2d@jalbum.net', 86, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Shepherd Ziemke', 6785057, 'lironside2e@google.com.hk', 87, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Skip Landis', 573013375, 'mmacdermott2f@histats.com', 88, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Stefanie Duberry', 256761149, 'amaccaghan2g@nymag.com', 89, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Stesha Daintith', 405157869, 'sgirton2h@trellian.com', 90, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Susette O''Gorman', 985127537, 'eattrie2i@springer.com', 91, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Tallia Bernardotti', 726765749, 'jmcconnal2j@imageshack.us', 92, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Teddy Cooke', 779475630, 'emeni2k@unc.edu', 93, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Teirtza Bernath', 366044861, 'ncorradino2l@netvibes.com', 94, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Weber Sawday', 961089178, 'rmasden2m@altervista.org', 95, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Wernher Vasilmanov', 891519967, 'clillyman2n@godaddy.com', 96, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Wiatt Boshier', 4541992, 'nfilinkov2o@japanpost.jp', 97, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Worth Channing', 516728131, 'crappport2p@cmu.edu', 98, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Yard Exter', 7811882, 'awills2q@ft.com', 99, 'Collector');
INSERT INTO urban_wasting_collection.staff (name, phone, email, id, type) VALUES ('Zedekiah Petworth', 53251225, 'lmccabe2r@shareasale.com', 100, 'Collector');
