USE CINEMA;
DROP TABLE IF EXISTS Movie_genres;

CREATE TABLE Movie_genres (
	Movie_code 		VARCHAR(9)	NOT NULL	REFERENCES Movie(Movie_code),
	Genres 			VARCHAR(50)	NOT NULL,
    PRIMARY KEY (Movie_code, Genres)
);

INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m00036050', 'Crime');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m00036050', 'Musical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m01089002', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m01089002', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m01811816', 'Crime');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m01811816', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m02068345', 'Mystery');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m02068345', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m03397093', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m03397093', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m03789410', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m03789410', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m04560481', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m04560481', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m04905601', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m04905601', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m06140924', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m06140924', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m06189028', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m06189028', 'Film-Noir');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m07894255', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m07894255', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m08256994', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m08256994', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m08269068', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m08269068', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m10030333', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m10030333', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m12968902', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m12968902', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m13604066', 'Film-Noir');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m13604066', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m14311756', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m14311756', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m15387336', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m15387336', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m15576089', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m15576089', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m19096654', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m19096654', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m19307593', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m19307593', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m19932012', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m19932012', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m21628403', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m21628403', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m22167169', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m22167169', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m23274579', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m23274579', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m23588678', 'War');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m23588678', 'Musical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m23947634', 'Historical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m23947634', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m25178503', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m25178503', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m26722206', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m26722206', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m26865850', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m26865850', 'Adventure');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m29716524', 'Crime');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m29716524', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m31281014', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m31281014', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m31709442', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m31709442', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m31930108', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m31930108', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m33633469', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m33633469', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m34307611', 'Film-Noir');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m34307611', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m34651114', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m34651114', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m36098720', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m36098720', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m37268580', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m37268580', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m39289033', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m39289033', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m41003528', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m41003528', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m41160635', 'Adventure');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m41160635', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m42705030', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m42705030', 'Historical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m44725767', 'Mystery');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m44725767', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m45203618', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m45203618', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m45391689', 'Crime');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m45391689', 'War');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m45836752', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m45836752', 'Mystery');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m46573100', 'Crime');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m46573100', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m47354433', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m47354433', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m48116842', 'War');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m48116842', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m50671370', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m50671370', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m51517121', 'Mystery');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m51517121', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m51574341', 'Historical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m51574341', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m53903586', 'Mystery');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m53903586', 'Crime');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m54969635', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m54969635', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m55300646', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m55300646', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m55319663', 'Mystery');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m55319663', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m57301478', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m57301478', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m58371615', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m58371615', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m58629216', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m58629216', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m59243291', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m59243291', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m59455748', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m59455748', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m59551317', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m59551317', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m60193694', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m60193694', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m61271264', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m61271264', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m61954213', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m61954213', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m62022016', 'Crime');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m62022016', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m62056443', 'Historical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m62056443', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m63305834', 'Science fiction');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m63305834', 'War');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m64263012', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m64263012', 'Science fiction');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m64267580', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m64267580', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m65686242', 'War');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m65686242', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m66791420', 'War');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m66791420', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m67771403', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m67771403', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m69670508', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m69670508', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m69707972', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m69707972', 'Film-Noir');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m71568090', 'Mystery');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m71568090', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m72390554', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m72390554', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m72640766', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m72640766', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m73006990', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m73006990', 'Film-Noir');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m78126847', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m78126847', 'Drama');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m79541185', 'Film-Noir');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m79541185', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m80106369', 'Fantasy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m80106369', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m80552946', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m80552946', 'Horror');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m80906605', 'Historical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m80906605', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m81482803', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m81482803', 'Science fiction');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m83761873', 'Animation');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m83761873', 'Action');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m83816154', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m83816154', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m84499891', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m84499891', 'Musical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m88277889', 'Historical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m88277889', 'Film-Noir');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m89779930', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m89779930', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m90427384', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m90427384', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m91258168', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m91258168', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m91645119', 'Action film');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m91645119', 'Western');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m92047561', 'Adventure');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m92047561', 'Thriller');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m92432288', 'Animated');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m92432288', 'Romance');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m93278499', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m93278499', 'Comedy');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m93457413', 'Historical');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m93457413', 'Adventure');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m93653336', 'Sci-Fi');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m93653336', 'Documentary');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m94589713', 'Children');
INSERT INTO Movie_genres (Movie_code, Genres) VALUES ('m94589713', 'Drama');
